### ISSUE TITLE
undefined method `<<' for nil:NilClass

### ISSUE THREAD

**Issue by nickcarenza** [nats-io/ruby-nats#128]
I am working on a logstash-output-plugin for nats and am hitting this error in ruby-nats:

```
{
  "timestamp": "2016-08-15T15:27:46.019000-0700",
  "message": "nats: Failed to send event to Nats",
  "event": { ... },
  "exception": "undefined method `<<' for nil:NilClass",
  "backtrace": [
    "/usr/local/Cellar/logstash/5.0.0-alpha3/libexec/vendor/bundle/jruby/1.9/gems/nats-0.8.0/lib/nats/client.rb:909:in `send_command'",
    "/usr/local/Cellar/logstash/5.0.0-alpha3/libexec/vendor/bundle/jruby/1.9/gems/nats-0.8.0/lib/nats/client.rb:378:in `publish'",
    "/usr/local/Cellar/logstash/5.0.0-alpha3/libexec/vendor/bundle/jruby/1.9/gems/nats-0.8.0/lib/nats/client.rb:256:in `publish'",
    "/usr/local/Cellar/logstash/5.0.0-alpha3/libexec/vendor/local_gems/bd0cc268/logstash-output-nats-1.0.0/lib/logstash/outputs/nats.rb:108:in `send_to_nats'",
    "org/jruby/RubyProc.java:281:in `call'",
    "/usr/local/Cellar/logstash/5.0.0-alpha3/libexec/vendor/bundle/jruby/1.9/gems/logstash-codec-json-3.0.1/lib/logstash/codecs/json.rb:42:in `encode'",
    "/usr/local/Cellar/logstash/5.0.0-alpha3/libexec/vendor/local_gems/bd0cc268/logstash-output-nats-1.0.0/lib/logstash/outputs/nats.rb:52:in `receive'",
    "/usr/local/Cellar/logstash/5.0.0-alpha3/libexec/vendor/bundle/jruby/1.9/gems/logstash-core-5.0.0.alpha3-java/lib/logstash/outputs/base.rb:87:in `multi_receive'",
    "org/jruby/RubyArray.java:1613:in `each'",
    "/usr/local/Cellar/logstash/5.0.0-alpha3/libexec/vendor/bundle/jruby/1.9/gems/logstash-core-5.0.0.alpha3-java/lib/logstash/outputs/base.rb:87:in `multi_receive'",
    "/usr/local/Cellar/logstash/5.0.0-alpha3/libexec/vendor/bundle/jruby/1.9/gems/logstash-core-5.0.0.alpha3-java/lib/logstash/output_delegator.rb:142:in `worker_multi_receive'",
    "/usr/local/Cellar/logstash/5.0.0-alpha3/libexec/vendor/bundle/jruby/1.9/gems/logstash-core-5.0.0.alpha3-java/lib/logstash/output_delegator.rb:123:in `multi_receive'",
    "/usr/local/Cellar/logstash/5.0.0-alpha3/libexec/vendor/bundle/jruby/1.9/gems/logstash-core-5.0.0.alpha3-java/lib/logstash/pipeline.rb:315:in `output_batch'",
    "org/jruby/RubyHash.java:1342:in `each'",
    "/usr/local/Cellar/logstash/5.0.0-alpha3/libexec/vendor/bundle/jruby/1.9/gems/logstash-core-5.0.0.alpha3-java/lib/logstash/pipeline.rb:315:in `output_batch'",
    "/usr/local/Cellar/logstash/5.0.0-alpha3/libexec/vendor/bundle/jruby/1.9/gems/logstash-core-5.0.0.alpha3-java/lib/logstash/pipeline.rb:243:in `worker_loop'",
    "/usr/local/Cellar/logstash/5.0.0-alpha3/libexec/vendor/bundle/jruby/1.9/gems/logstash-core-5.0.0.alpha3-java/lib/logstash/pipeline.rb:204:in `start_workers'"
  ],
  "level": "warn"
}
```

ruby-nats https://github.com/nats-io/ruby-nats/blob/v0.8.0/lib/nats/client.rb#L909

```
  def send_command(command, priority = false) #:nodoc:
    needs_flush = (connected? && @pending.nil?)

    @pending ||= []
    @pending << command unless priority
    @pending.unshift(command) if priority
    @pending_size += command.bytesize
```

Is the case that `@pending` is being set to nil somehow after it is `||=`ed to `[]`?

I tried to test this with irb but it seems to work fine (assuming that, given the error message, `pending` is nil coming into this function):

```
irb(main):010:0> pending = nil
=> nil
irb(main):010:0> pending.nil?
=> true
irb(main):011:0> pending ||= []
=> []
irb(main):012:0> pending
=> []
irb(main):013:0> pending << 'command' unless false
=> ["command"]
```

I am new to ruby and not at all familiar with eventmachine, maybe something in there allowing this to happen?

Of course it could be something I am doing wrong in my plugin at https://github.com/nickcarenza/logstash-output-nats.

**Comment by wallyqs** [comment]
Hi, thanks for the report... This is similar to #118 related to the thread safety of the gem since NATS it is being started in its own thread [here](https://github.com/nickcarenza/logstash-output-nats/blob/c3c74f56f01c362d670a1d51eceeccad4d8b567a/lib/logstash/outputs/nats.rb#L98) while publishes happen in [another thread](https://github.com/nickcarenza/logstash-output-nats/blob/c3c74f56f01c362d670a1d51eceeccad4d8b567a/lib/logstash/outputs/nats.rb#L108).

**Comment by wallyqs** [comment]
For a thread safe version of the gem, this version of the gem can be used instead, it also supports jruby runtimes:
https://github.com/nats-io/pure-ruby-nats
